name: Bike and Sol
favicon: null
layout_spectrum: 0.47888472699560225
typography_spectrum: 0.8121453360654414
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.25424484303221107
  lightness: 0.9894829611293972
  saturation: 0.682423293357715
  rhythmicContrast: 0.11504552769474685
purpose: []
